### ISSUE TITLE
Error when running bam2sam.py

### ISSUE THREAD

**Issue by tnstylia** [jhart99/bam2fastq#4]
Hi jhart99,

Thanks for creating the bam2sam.py script. Can you please help me out with the following error?  When I first ran it, it threw an error and suggested I add parenthesis after every "print" command you had (i.e. line 211: print (pair.sam)). After doing so, I get the following error:

using Python 2.7
(base) [tnstylia@trident1 bam2fastq-master]$ python2 bam2sam.py humanOnly.bam   Traceback (most recent call last):
  File "bam2sam.py", line 245, in <module>
    main()
  File "bam2sam.py", line 241, in main
    in_bam.get_read_pairs()
  File "bam2sam.py", line 211, in get_read_pairs
    print (pair.sam)
  File "bam2sam.py", line 72, in sam
    attrib = "RG:Z:{rg}".format(rg=self.read_group)
AttributeError: 'SamLine' object has no attribute 'read_group'

Using python3:
(base) [tnstylia@trident1 bam2fastq-master]$ python bam2sam.py humanOnly.bam    Traceback (most recent call last):
  File "bam2sam.py", line 245, in <module>
    main()
  File "bam2sam.py", line 237, in main
    in_bam = Bam(args.bam)
  File "bam2sam.py", line 106, in __init__
    self.contigs = self._get_contigs()
  File "bam2sam.py", line 144, in _get_contigs
    self._get_header()
  File "bam2sam.py", line 135, in _get_header
    header_fields = line.split("\t")
TypeError: a bytes-like object is required, not 'str'
(base) [tnstylia@trident1 bam2fastq-master]$

If I give it a sam file instead, it throws this error for both python 2.7 and 3:

(base) [tnstylia@trident1 bam2fastq-master]$ python2 bam2sam.py humanOnlysam.sam
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from "humanOnlysam.sam".
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from "humanOnlysam.sam".
Traceback (most recent call last):
  File "bam2sam.py", line 245, in <module>
    main()
  File "bam2sam.py", line 241, in main
    in_bam.get_read_pairs()
  File "bam2sam.py", line 221, in get_read_pairs
    last_line = line
UnboundLocalError: local variable 'line' referenced before assignment

Thank you and sorry if there is an obvious solution, I am new to this. 

Nataly

EDIT; The bam file is an output from STAR

**Comment by jhart99** [comment]
Working on this now.  Would it be possible to send me a small piece of the file to make sure the fix I made works with your data?

**Comment by tnstylia** [comment]
Hi Jonathan,

Thank you, I have clipped the top 10,000 lines of one of my bam files using the following:

samtools view -h -b  Genome.bam | head -10000  > test.bam

Hopefully that will work for you?

I have attached test.bam
